-- PostgreSQL/Supabase conversion of database/blessed.sql
-- Paste this file into the Supabase SQL Editor.
-- Generated for schema: u937180775_bblessed_db

BEGIN;

DROP TABLE IF EXISTS "walk_in_items" CASCADE;
DROP TABLE IF EXISTS "walk_in" CASCADE;
DROP TABLE IF EXISTS "reservation_items" CASCADE;
DROP TABLE IF EXISTS "reservations" CASCADE;
DROP TABLE IF EXISTS "registers_tb" CASCADE;
DROP TABLE IF EXISTS "purchase_items" CASCADE;
DROP TABLE IF EXISTS "purchase" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "notifications" CASCADE;
DROP TABLE IF EXISTS "notifcustomer" CASCADE;
DROP TABLE IF EXISTS "notifadmin" CASCADE;
DROP TABLE IF EXISTS "log_history_tb" CASCADE;
DROP TABLE IF EXISTS "login_tb" CASCADE;
DROP TABLE IF EXISTS "inventory" CASCADE;
DROP TABLE IF EXISTS "forgot_password_tb" CASCADE;
DROP TABLE IF EXISTS "category" CASCADE;
DROP TABLE IF EXISTS "cart_items" CASCADE;
DROP TABLE IF EXISTS "cart" CASCADE;
DROP TABLE IF EXISTS "audit_logs" CASCADE;
DROP TABLE IF EXISTS "admin_login_tb" CASCADE;
DROP TABLE IF EXISTS "admin_list_login_tb" CASCADE;
DROP TABLE IF EXISTS "admin_forgot_tb" CASCADE;

CREATE TABLE "admin_forgot_tb" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" varchar(255) NOT NULL,
    "code" varchar(10) NOT NULL,
    "password" varchar(255),
    "date_time" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "admin_forgot_tb_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "admin_list_login_tb" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email" varchar(255) NOT NULL,
    "Password" varchar(255) NOT NULL,
    "Login_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "admin_list_login_tb_pkey" PRIMARY KEY ("ID")
);

CREATE TABLE "admin_login_tb" (
    "admin_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,
    "login_TnD" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "admin_login_tb_pkey" PRIMARY KEY ("admin_id")
);

CREATE TABLE "audit_logs" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "role" varchar(50) NOT NULL,
    "task_performed" text NOT NULL,
    "date_time" timestamp without time zone NOT NULL,
    CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cart" (
    "cart_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "login_id" integer NOT NULL,
    "total" numeric(10,2) DEFAULT 0.00,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "cart_pkey" PRIMARY KEY ("cart_id")
);

CREATE TABLE "cart_items" (
    "cart_items_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "cart_id" integer NOT NULL,
    "product_id" integer NOT NULL,
    "quantity" integer NOT NULL,
    "amount" numeric(10,2) NOT NULL,
    "add_date" timestamp without time zone,
    CONSTRAINT "cart_items_pkey" PRIMARY KEY ("cart_items_id")
);

CREATE TABLE "category" (
    "category_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "category_name" varchar(100) NOT NULL,
    CONSTRAINT "category_pkey" PRIMARY KEY ("category_id")
);

CREATE TABLE "forgot_password_tb" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" integer NOT NULL,
    "email" varchar(255) NOT NULL,
    "token" varchar(255) NOT NULL,
    "code" varchar(10) NOT NULL,
    "expires_at" timestamp without time zone NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "forgot_password_tb_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "inventory" (
    "inventory_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "product_id" integer NOT NULL,
    "stocks" integer DEFAULT 0,
    "sold_count" integer DEFAULT 0,
    CONSTRAINT "inventory_pkey" PRIMARY KEY ("inventory_id")
);

CREATE TABLE "login_tb" (
    "login_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "register_id" integer NOT NULL,
    CONSTRAINT "login_tb_pkey" PRIMARY KEY ("login_id")
);

CREATE TABLE "log_history_tb" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" varchar(100) NOT NULL,
    "password" varchar(255) NOT NULL,
    "status" varchar(20) CHECK ("status" IN ('Login', 'Logout')) NOT NULL,
    "dateandtime" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "log_history_tb_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "notifadmin" (
    "notif_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "register_id" integer NOT NULL,
    "notif_message" text NOT NULL,
    "notif_type" varchar(50) NOT NULL,
    "notif_link" varchar(255),
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "is_read" smallint DEFAULT 0,
    CONSTRAINT "notifadmin_pkey" PRIMARY KEY ("notif_id")
);

CREATE TABLE "notifcustomer" (
    "notif_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "register_id" integer NOT NULL,
    "notif_message" text NOT NULL,
    "notif_type" varchar(50) NOT NULL,
    "notif_link" varchar(255),
    "reference_id" integer,
    "created_at" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    "is_read" smallint DEFAULT 0,
    CONSTRAINT "notifcustomer_pkey" PRIMARY KEY ("notif_id")
);

CREATE TABLE "notifications" (
    "notification_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "register_id" integer NOT NULL,
    "type" varchar(50) NOT NULL,
    "title" varchar(255) NOT NULL,
    "message" text NOT NULL,
    "cart_items_id" integer,
    "reservation_id" integer,
    "status" varchar(20) CHECK ("status" IN ('unread', 'read')) DEFAULT 'unread',
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamp without time zone,
    CONSTRAINT "notifications_pkey" PRIMARY KEY ("notification_id")
);

CREATE TABLE "products" (
    "product_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "category_id" integer NOT NULL,
    "product_name" varchar(150) NOT NULL,
    "price" numeric(10,2) NOT NULL,
    "image_path" varchar(255),
    CONSTRAINT "products_pkey" PRIMARY KEY ("product_id")
);

CREATE TABLE "purchase" (
    "purchase_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "walk_in_id" integer,
    "reservation_id" integer,
    "totalAmount" numeric(10,2) NOT NULL,
    "purchaseMethod" varchar(225) NOT NULL,
    "purchaseDate" date NOT NULL,
    CONSTRAINT "purchase_pkey" PRIMARY KEY ("purchase_id")
);

CREATE TABLE "purchase_items" (
    "purchase_item_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "purchase_id" integer NOT NULL,
    "product_id" integer NOT NULL,
    "quantity" integer NOT NULL,
    "amount" numeric(10,2) NOT NULL,
    CONSTRAINT "purchase_items_pkey" PRIMARY KEY ("purchase_item_id")
);

CREATE TABLE "registers_tb" (
    "register_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "register_fname" varchar(255) NOT NULL,
    "register_lname" varchar(255) NOT NULL,
    "register_email" varchar(255) NOT NULL,
    "phone_number" varchar(255) NOT NULL,
    "register_password" varchar(255) NOT NULL,
    "created_at" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "registers_tb_pkey" PRIMARY KEY ("register_id")
);

CREATE TABLE "reservations" (
    "reservation_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "register_id" integer NOT NULL,
    "total" integer NOT NULL,
    "status" varchar(50) NOT NULL,
    "reservation_date" date NOT NULL,
    "pickup_date" date,
    "date_picked_up" date,
    "cancel_date" date,
    CONSTRAINT "reservations_pkey" PRIMARY KEY ("reservation_id")
);

CREATE TABLE "reservation_items" (
    "reservation_item_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "reservation_id" integer NOT NULL,
    "product_id" integer NOT NULL,
    "quantity" integer NOT NULL,
    CONSTRAINT "reservation_items_pkey" PRIMARY KEY ("reservation_item_id")
);

CREATE TABLE "walk_in" (
    "walk_in_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "walk_in_name" varchar(255),
    "total" integer NOT NULL,
    "walk_in_date" date NOT NULL,
    CONSTRAINT "walk_in_pkey" PRIMARY KEY ("walk_in_id")
);

CREATE TABLE "walk_in_items" (
    "walk_in_item_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "walk_in_id" integer NOT NULL,
    "product_id" integer NOT NULL,
    "quantity" integer NOT NULL,
    CONSTRAINT "walk_in_items_pkey" PRIMARY KEY ("walk_in_item_id")
);

INSERT INTO "admin_login_tb" ("admin_id", "email", "password", "login_TnD") VALUES
(1, 'beautyandblessed2@gmail.com', '$2y$10$1BfEA69CAvu50eH6bKls.OcwvpdBaluBhUlTmfU4KA8nT49sL.cwu', '2025-09-26 06:51:59')
;

INSERT INTO "category" ("category_id", "category_name") VALUES
(1, 'Perfumes'),
(2, 'Sunscreens'),
(3, 'Concealer'),
(4, 'Blush'),
(5, 'Nails'),
(6, 'Body Soaps'),
(7, 'Contact Lenses'),
(8, 'Hair Oil'),
(9, 'Palette'),
(10, 'Brush'),
(11, 'Ointments'),
(15, 'Sample'),
(17, 'Gell')
;

INSERT INTO "log_history_tb" ("id", "email", "password", "status", "dateandtime") VALUES
(1, 'beautyandblessed2@gmail.com', '$2y$10$1BfEA69CAvu50eH6bKls.OcwvpdBaluBhUlTmfU4KA8nT49sL.cwu', 'Login', '2026-05-03 00:26:46'),
(2, 'beautyandblessed2@gmail.com', '$2y$10$1BfEA69CAvu50eH6bKls.OcwvpdBaluBhUlTmfU4KA8nT49sL.cwu', 'Login', '2026-05-22 02:39:56')
;

INSERT INTO "products" ("product_id", "category_id", "product_name", "price", "image_path") VALUES
(1, 1, 'Victoria Secret – Romantic', 650.00, 'romantic.jpg'),
(2, 1, 'Victoria Secret – Love Spell', 800.00, 'pictures/perfume/lovespell.jpg'),
(3, 1, 'Victoria Secret – Pure Seduction', 800.00, 'seduction.jpg'),
(4, 1, 'Victoria Secret – Love Spell Shimmer', 900.00, 'pictures/perfume/shimmer.jpg'),
(5, 2, 'Karite Sunscreen SFP50 Waterproof', 250.00, 'pictures/suncreen/waterproof.jpg'),
(6, 2, 'Karite 2 in 1 Nourish Skin IV Protective SFP50', 280.00, 'pictures/suncreen/nourish.jpg'),
(7, 2, 'Whitening Sunscreen Lotion SFP50', 300.00, 'pictures/suncreen/whitening.jpg'),
(8, 2, 'Disaar Sunscreen Bronz foundation SFP50', 320.00, 'pictures/suncreen/disaar.jpg'),
(9, 2, 'Goree Day and Night Beauty Cream', 200.00, 'pictures/suncreen/goree.jpg'),
(10, 3, 'PRO Concealer Cream', 180.00, 'pictures/concealer/cream.jpg'),
(11, 3, 'PRO Concealer Peach', 180.00, 'pictures/concealer/peach.jpg'),
(12, 3, 'PRO Concealer Green', 180.00, 'pictures/concealer/green.jpg'),
(13, 3, 'PRO Concealer Yellow', 180.00, 'pictures/concealer/yellow.jpg'),
(14, 3, 'PRO Concealer Brown', 180.00, 'pictures/concealer/brown.jpg'),
(15, 4, 'Kiss Beauty – Lips and Cheeks Color Change', 170.00, 'pictures/blushon/colorchange.jpg'),
(16, 4, 'Kiss Beauty – Blush Sweet', 160.00, 'pictures/blushon/blushsweet.jpg'),
(17, 4, 'Kiss Beauty – Magic Blusher', 170.00, 'pictures/blushon/magic.jpg'),
(18, 5, 'NXS01', 120.00, 'pictures/nails/nx01.jpg'),
(19, 5, 'NXS02', 120.00, 'pictures/nails/nx02.jpg'),
(20, 5, 'NXS03', 120.00, 'pictures/nails/nx03.jpg'),
(21, 5, 'NXS04', 120.00, 'pictures/nails/nx04.jpg'),
(22, 5, 'NXS05', 120.00, 'pictures/nails/nx05.jpg'),
(23, 6, 'Safi – Mencerah and Menghidrat', 200.00, 'pictures/soap/mencerah.jpg'),
(24, 6, 'Safi – Melembut and Menyegar', 200.00, 'pictures/soap/melembut.jpg'),
(25, 6, 'Safi – Anti Jerawat', 220.00, 'pictures/soap/antijewart.jpg'),
(26, 6, 'Safi – Mencerah and Menyari', 220.00, 'pictures/soap/menyari.jpg'),
(27, 6, 'Safi – Mengawal Minyak and Mencera', 220.00, 'pictures/soap/mengawal.jpg'),
(28, 7, 'Girl Contact Lenses Sterile (Brown Color)', 300.00, 'pictures/lense/brown.jpg'),
(29, 7, 'Girl Contact Lenses Sterile (Barbie Eye)', 300.00, 'pictures/lense/barbieye.jpg'),
(30, 7, 'Girl Contact Lenses Sterile (Gray Color)', 300.00, 'pictures/lense/gray.jpg'),
(31, 7, 'Girl Contact Lenses Sterile (Cloud Gray)', 320.00, 'pictures/lense/cloud.jpg'),
(32, 7, 'Girl Contact Lenses Sterile (Star Brown)', 320.00, 'pictures/lense/star.jpg'),
(33, 8, 'Kenspeckle – HSE01', 200.00, 'pictures/haircare/hse01.jpg'),
(34, 8, 'Kenspeckle – HSE02', 200.00, 'pictures/haircare/hse02.jpg'),
(35, 8, 'Kenspeckle – HSE03', 200.00, 'pictures/haircare/hse03.jpg'),
(36, 8, 'Kenspeckle – HSE04', 200.00, 'pictures/haircare/hse04.jpg'),
(37, 8, 'Kenspeckle – HSE05', 200.00, 'pictures/haircare/hse05.jpg'),
(38, 9, 'Kiss Beauty – Peach Blossom', 350.00, 'pictures/palette/peach.png'),
(39, 9, 'S.f.r color Glitter', 380.00, 'pictures/palette/glitter.png'),
(40, 9, 'S.f.r Wild Jaguar', 380.00, 'pictures/palette/wild.jpg'),
(41, 9, 'Kiss Beauty 4in1 Baked Highlight', 400.00, 'pictures/palette/baked.jpg'),
(42, 9, 'Glow Palette Limited Edition', 450.00, 'pictures/palette/limited.jpg'),
(43, 10, 'Pink Key – Beautify your beauty', 280.00, 'pictures/brush/pinkkey.jpg'),
(44, 10, 'Sweet Beauty – Spongebob', 300.00, 'pictures/brush/spongebob.jpg'),
(45, 10, 'Sweet Beauty – Beauty Tools', 300.00, 'pictures/brush/beauty.jpg'),
(46, 10, 'GR New Make up brush Set', 350.00, 'pictures/brush/newmake.jpg'),
(47, 10, 'Mermaid Like Brushes', 400.00, 'pictures/brush/mermaid.jpg'),
(48, 11, 'Minyak Terapi', 150.00, 'pictures/panghilot/minyak.jpg'),
(49, 11, 'Arima Theraphy Lemon', 120.00, 'pictures/panghilot/aroma.jpg'),
(50, 11, 'Chiom Chengki Lemon', 160.00, 'pictures/panghilot/chiom.jpg'),
(51, 11, 'Kwan Loong Medicated Oil', 180.00, 'kwanloong.jpg'),
(55, 3, 'PRO Concealer Cream', 120.00, ''),
(57, 17, 'sample', 120.00, '1764569507_Screenshot 2025-12-01 004149.png')
;

CREATE INDEX "idx_forgot_password_tb_fk_register" ON "forgot_password_tb" ("user_id");
CREATE INDEX "idx_inventory_product_id" ON "inventory" ("product_id");
CREATE INDEX "idx_products_category_id" ON "products" ("category_id");
CREATE INDEX "idx_walk_in_items_walk_in_id" ON "walk_in_items" ("walk_in_id");
CREATE INDEX "idx_walk_in_items_product_id" ON "walk_in_items" ("product_id");

ALTER TABLE "products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "category" ("category_id") ON DELETE CASCADE ON UPDATE CASCADE;

SELECT setval(pg_get_serial_sequence('admin_forgot_tb', 'id'), COALESCE((SELECT MAX("id") FROM "admin_forgot_tb"), 1), (SELECT MAX("id") IS NOT NULL FROM "admin_forgot_tb"));
SELECT setval(pg_get_serial_sequence('admin_list_login_tb', 'ID'), COALESCE((SELECT MAX("ID") FROM "admin_list_login_tb"), 1), (SELECT MAX("ID") IS NOT NULL FROM "admin_list_login_tb"));
SELECT setval(pg_get_serial_sequence('admin_login_tb', 'admin_id'), COALESCE((SELECT MAX("admin_id") FROM "admin_login_tb"), 1), (SELECT MAX("admin_id") IS NOT NULL FROM "admin_login_tb"));
SELECT setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE((SELECT MAX("id") FROM "audit_logs"), 1), (SELECT MAX("id") IS NOT NULL FROM "audit_logs"));
SELECT setval(pg_get_serial_sequence('cart', 'cart_id'), COALESCE((SELECT MAX("cart_id") FROM "cart"), 1), (SELECT MAX("cart_id") IS NOT NULL FROM "cart"));
SELECT setval(pg_get_serial_sequence('cart_items', 'cart_items_id'), COALESCE((SELECT MAX("cart_items_id") FROM "cart_items"), 1), (SELECT MAX("cart_items_id") IS NOT NULL FROM "cart_items"));
SELECT setval(pg_get_serial_sequence('category', 'category_id'), COALESCE((SELECT MAX("category_id") FROM "category"), 1), (SELECT MAX("category_id") IS NOT NULL FROM "category"));
SELECT setval(pg_get_serial_sequence('forgot_password_tb', 'id'), COALESCE((SELECT MAX("id") FROM "forgot_password_tb"), 1), (SELECT MAX("id") IS NOT NULL FROM "forgot_password_tb"));
SELECT setval(pg_get_serial_sequence('inventory', 'inventory_id'), COALESCE((SELECT MAX("inventory_id") FROM "inventory"), 1), (SELECT MAX("inventory_id") IS NOT NULL FROM "inventory"));
SELECT setval(pg_get_serial_sequence('login_tb', 'login_id'), COALESCE((SELECT MAX("login_id") FROM "login_tb"), 1), (SELECT MAX("login_id") IS NOT NULL FROM "login_tb"));
SELECT setval(pg_get_serial_sequence('log_history_tb', 'id'), COALESCE((SELECT MAX("id") FROM "log_history_tb"), 1), (SELECT MAX("id") IS NOT NULL FROM "log_history_tb"));
SELECT setval(pg_get_serial_sequence('notifadmin', 'notif_id'), COALESCE((SELECT MAX("notif_id") FROM "notifadmin"), 1), (SELECT MAX("notif_id") IS NOT NULL FROM "notifadmin"));
SELECT setval(pg_get_serial_sequence('notifcustomer', 'notif_id'), COALESCE((SELECT MAX("notif_id") FROM "notifcustomer"), 1), (SELECT MAX("notif_id") IS NOT NULL FROM "notifcustomer"));
SELECT setval(pg_get_serial_sequence('notifications', 'notification_id'), COALESCE((SELECT MAX("notification_id") FROM "notifications"), 1), (SELECT MAX("notification_id") IS NOT NULL FROM "notifications"));
SELECT setval(pg_get_serial_sequence('products', 'product_id'), COALESCE((SELECT MAX("product_id") FROM "products"), 1), (SELECT MAX("product_id") IS NOT NULL FROM "products"));
SELECT setval(pg_get_serial_sequence('purchase', 'purchase_id'), COALESCE((SELECT MAX("purchase_id") FROM "purchase"), 1), (SELECT MAX("purchase_id") IS NOT NULL FROM "purchase"));
SELECT setval(pg_get_serial_sequence('purchase_items', 'purchase_item_id'), COALESCE((SELECT MAX("purchase_item_id") FROM "purchase_items"), 1), (SELECT MAX("purchase_item_id") IS NOT NULL FROM "purchase_items"));
SELECT setval(pg_get_serial_sequence('registers_tb', 'register_id'), COALESCE((SELECT MAX("register_id") FROM "registers_tb"), 1), (SELECT MAX("register_id") IS NOT NULL FROM "registers_tb"));
SELECT setval(pg_get_serial_sequence('reservations', 'reservation_id'), COALESCE((SELECT MAX("reservation_id") FROM "reservations"), 1), (SELECT MAX("reservation_id") IS NOT NULL FROM "reservations"));
SELECT setval(pg_get_serial_sequence('reservation_items', 'reservation_item_id'), COALESCE((SELECT MAX("reservation_item_id") FROM "reservation_items"), 1), (SELECT MAX("reservation_item_id") IS NOT NULL FROM "reservation_items"));
SELECT setval(pg_get_serial_sequence('walk_in', 'walk_in_id'), COALESCE((SELECT MAX("walk_in_id") FROM "walk_in"), 1), (SELECT MAX("walk_in_id") IS NOT NULL FROM "walk_in"));
SELECT setval(pg_get_serial_sequence('walk_in_items', 'walk_in_item_id'), COALESCE((SELECT MAX("walk_in_item_id") FROM "walk_in_items"), 1), (SELECT MAX("walk_in_item_id") IS NOT NULL FROM "walk_in_items"));

COMMIT;
