<?php
$source = __DIR__ . '/../database/blessed.sql';
$target = __DIR__ . '/../database/blessed_supabase.sql';

$text = file_get_contents($source);
if ($text === false) {
    fwrite(STDERR, "Unable to read source SQL file.\n");
    exit(1);
}

$identityCols = [
    'admin_forgot_tb' => 'id',
    'admin_list_login_tb' => 'ID',
    'admin_login_tb' => 'admin_id',
    'audit_logs' => 'id',
    'cart' => 'cart_id',
    'cart_items' => 'cart_items_id',
    'category' => 'category_id',
    'forgot_password_tb' => 'id',
    'inventory' => 'inventory_id',
    'login_tb' => 'login_id',
    'log_history_tb' => 'id',
    'notifadmin' => 'notif_id',
    'notifcustomer' => 'notif_id',
    'notifications' => 'notification_id',
    'products' => 'product_id',
    'purchase' => 'purchase_id',
    'purchase_items' => 'purchase_item_id',
    'registers_tb' => 'register_id',
    'reservations' => 'reservation_id',
    'reservation_items' => 'reservation_item_id',
    'walk_in' => 'walk_in_id',
    'walk_in_items' => 'walk_in_item_id',
];

$primaryKeys = [
    'admin_forgot_tb' => ['id'],
    'admin_list_login_tb' => ['ID'],
    'admin_login_tb' => ['admin_id'],
    'audit_logs' => ['id'],
    'cart' => ['cart_id'],
    'cart_items' => ['cart_items_id'],
    'category' => ['category_id'],
    'forgot_password_tb' => ['id'],
    'inventory' => ['inventory_id'],
    'login_tb' => ['login_id'],
    'log_history_tb' => ['id'],
    'notifadmin' => ['notif_id'],
    'notifcustomer' => ['notif_id'],
    'notifications' => ['notification_id'],
    'products' => ['product_id'],
    'purchase' => ['purchase_id'],
    'purchase_items' => ['purchase_item_id'],
    'registers_tb' => ['register_id'],
    'reservations' => ['reservation_id'],
    'reservation_items' => ['reservation_item_id'],
    'walk_in' => ['walk_in_id'],
    'walk_in_items' => ['walk_in_item_id'],
];

$indexes = [
    ['forgot_password_tb', 'fk_register', ['user_id']],
    ['inventory', 'product_id', ['product_id']],
    ['products', 'category_id', ['category_id']],
    ['walk_in_items', 'walk_in_id', ['walk_in_id']],
    ['walk_in_items', 'product_id', ['product_id']],
];

function q($name) {
    return '"' . str_replace('"', '""', $name) . '"';
}

function convertColumn($table, $column, $definition, $identityCols) {
    $definition = trim(rtrim($definition, ','));
    $definition = preg_replace('/\bUNSIGNED\b/i', '', $definition);
    $definition = preg_replace('/\s+/', ' ', $definition);

    $notNull = preg_match('/\bNOT NULL\b/i', $definition) === 1;
    $default = null;
    if (preg_match('/\bDEFAULT\s+([^ ]+(?:\s*\([^)]*\))?)/i', $definition, $match)) {
        $default = rtrim($match[1], ',');
        if (strtolower($default) === 'current_timestamp()') {
            $default = 'CURRENT_TIMESTAMP';
        } elseif (strtolower($default) === 'null') {
            $default = null;
        }
    }

    if (($identityCols[$table] ?? null) === $column) {
        $type = 'integer GENERATED BY DEFAULT AS IDENTITY';
    } elseif (preg_match('/^int\(\d+\)/i', $definition)) {
        $type = 'integer';
    } elseif (preg_match('/^tinyint\(1\)/i', $definition)) {
        $type = 'smallint';
    } elseif (preg_match('/^decimal\((\d+),(\d+)\)/i', $definition, $match)) {
        $type = 'numeric(' . $match[1] . ',' . $match[2] . ')';
    } elseif (preg_match('/^varchar\((\d+)\)/i', $definition, $match)) {
        $type = 'varchar(' . $match[1] . ')';
    } elseif (preg_match('/^text\b/i', $definition)) {
        $type = 'text';
    } elseif (preg_match('/^timestamp\b/i', $definition)) {
        $type = 'timestamp without time zone';
    } elseif (preg_match('/^datetime\b/i', $definition)) {
        $type = 'timestamp without time zone';
    } elseif (preg_match('/^date\b/i', $definition)) {
        $type = 'date';
    } elseif (preg_match("/^enum\('unread','read'\)/i", $definition)) {
        $type = 'varchar(20) CHECK (' . q($column) . " IN ('unread', 'read'))";
    } elseif (preg_match("/^enum\('Login','Logout'\)/i", $definition)) {
        $type = 'varchar(20) CHECK (' . q($column) . " IN ('Login', 'Logout'))";
    } else {
        throw new RuntimeException("Unhandled type for {$table}.{$column}: {$definition}");
    }

    $parts = [q($column), $type];
    if ($table === 'purchase' && $column === 'reservation_id') {
        $notNull = false;
    }

    if ($notNull) {
        $parts[] = 'NOT NULL';
    }
    if ($default !== null && (($identityCols[$table] ?? null) !== $column)) {
        $parts[] = 'DEFAULT ' . $default;
    }

    return '    ' . implode(' ', $parts);
}

$output = [
    '-- PostgreSQL/Supabase conversion of database/blessed.sql',
    '-- Paste this file into the Supabase SQL Editor.',
    '-- Generated for schema: u937180775_bblessed_db',
    '',
    'BEGIN;',
    '',
];

preg_match_all('/CREATE TABLE `([^`]+)` \(/', $text, $tableMatches);
$tables = $tableMatches[1];
foreach (array_reverse($tables) as $table) {
    $output[] = 'DROP TABLE IF EXISTS ' . q($table) . ' CASCADE;';
}
$output[] = '';

preg_match_all('/CREATE TABLE `([^`]+)` \((.*?)\) ENGINE=/s', $text, $createMatches, PREG_SET_ORDER);
foreach ($createMatches as $createMatch) {
    $table = $createMatch[1];
    $body = $createMatch[2];
    $columns = [];
    foreach (preg_split('/\R/', $body) as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] !== '`') {
            continue;
        }
        if (!preg_match('/`([^`]+)`\s+(.+)/', $line, $columnMatch)) {
            continue;
        }
        $columns[] = convertColumn($table, $columnMatch[1], $columnMatch[2], $identityCols);
    }

    if (isset($primaryKeys[$table])) {
        $pkCols = array_map('q', $primaryKeys[$table]);
        $columns[] = '    CONSTRAINT ' . q($table . '_pkey') . ' PRIMARY KEY (' . implode(', ', $pkCols) . ')';
    }

    $output[] = 'CREATE TABLE ' . q($table) . ' (';
    $output[] = implode(",\n", $columns);
    $output[] = ');';
    $output[] = '';
}

preg_match_all('/INSERT INTO `([^`]+)` \((.*?)\) VALUES\n(.*?);/s', $text, $insertMatches, PREG_SET_ORDER);
foreach ($insertMatches as $insertMatch) {
    $table = $insertMatch[1];
    preg_match_all('/`([^`]+)`/', $insertMatch[2], $columnMatches);
    $columns = $columnMatches[1];
    $values = str_replace("\\'", "''", $insertMatch[3]);

    $output[] = 'INSERT INTO ' . q($table) . ' (' . implode(', ', array_map('q', $columns)) . ') VALUES';
    $output[] = $values;
    $output[] = ';';
    $output[] = '';
}

foreach ($indexes as [$table, $name, $columns]) {
    $output[] = 'CREATE INDEX ' . q('idx_' . $table . '_' . $name) . ' ON ' . q($table) . ' (' . implode(', ', array_map('q', $columns)) . ');';
}
$output[] = '';

$output[] = 'ALTER TABLE "products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "category" ("category_id") ON DELETE CASCADE ON UPDATE CASCADE;';
$output[] = '';

foreach ($identityCols as $table => $column) {
    $safeTable = str_replace("'", "''", $table);
    $safeColumn = str_replace("'", "''", $column);
    $output[] = "SELECT setval(pg_get_serial_sequence('{$safeTable}', '{$safeColumn}'), COALESCE((SELECT MAX(" . q($column) . ') FROM ' . q($table) . "), 1), (SELECT MAX(" . q($column) . ') IS NOT NULL FROM ' . q($table) . '));';
}

$output[] = '';
$output[] = 'COMMIT;';
$output[] = '';

file_put_contents($target, implode("\n", $output));
echo "Wrote {$target}\n";
